baseurl = "/"
# languageCode = "en-us"
title = "rOpenSci - open tools for open science"
theme = "ropensci"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]
footnotereturnlinkcontents = "â†©"

paginate = 5
paginatePath = "page"

[permalinks]
    blog = "/blog/:year/:month/:day/:slug/"
    technotes = "/technotes/:year/:month/:day/:slug/"

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 2
[[menu.main]]
    name = "Categories"
    url = "/categories/"
    weight = 3
[[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 4
[[menu.main]]
    name = "Subscribe"
    url = "/index.xml"

[params]
    description = "rOpenSci - Open Tools for Open Science"
    footer = "&copy; The rOpenSci Project"
    leadership = ["Carl Boettiger", "Karthik Ram", "Scott Chamberlain", "Jenny Bryan", "Rich FitzJohn", "Leadership Team", "Core Team"]
    staff = ["Jeroen Ooms", "Stefanie Butland"]

[taxonomies]
  tag = "tags"

