[build]
  command = "hugo -F"

[context.production.environment]
  HUGO_VERSION = "0.72.0"

[context.deploy-preview.environment]
  HUGO_VERSION = "0.72.0"
  
[context.deploy-preview]
  command = "hugo -b $DEPLOY_PRIME_URL"

[context.branch-deploy]
  command = "hugo -b $DEPLOY_PRIME_URL"
