name = "ropensci"
license = "MIT"
licenselink = "https://github.com/ropensci/roweb/blob/master/LICENSE.md"
description = ""
homepage = "http://ropensci.org/"
tags = []
features = []
min_version = "0.20"


